Item card
trisandyatechnologies/ecom pull request #11
Opened 2024-01-08 07:02 UTC by NamburiYaswanth

![image](https://github.com/trisandyatechnologies/ecom/assets/112677183/94823fd9-f6c0-497e-a3b4-7b7ef3a42b2b)

2024-01-08 07:06 UTC, tulasikurete approved these changes

2024-01-08 07:09 UTC, NagaDurga16 approved these changes

2024-01-08 09:02 UTC, Namahsivaya7 commented
please add space between images and their titles

2024-01-08 09:03 UTC, Namahsivaya7 commented
where is mobile view

2024-01-08 09:05 UTC, Namahsivaya7 commented
page width must be 100% but it is morethan that

2024-01-10 05:21 UTC, arajajyothibabu submitted a review, later dismissed

2024-01-10 13:42 UTC, arajajyothibabu requested changes

2024-01-10 13:42 UTC, arajajyothibabu commented on src/app/checkoutpage/page.tsx
> +const CheckOut: React.FC = () => (
Remove this file and changes from this PR

2024-01-10 14:44 UTC, arajajyothibabu approved these changes
LGTM

2024-01-10 14:45 UTC, merged