userProfile
trisandyatechnologies/ecom pull request #14
Opened 2024-01-10 06:02 UTC by tulasikurete

![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/e5a7aaac-c656-470d-a3e1-705a8015a8bc)

2024-01-10 07:24 UTC, tulasikurete commented
![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/4ec658fd-f9eb-4c0c-9809-946fa8f38837)
![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/f7cb3855-573b-4f19-8356-b6498db66a24)
![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/27deb3a3-6320-42cf-8549-1f081be8abf2)

2024-01-10 13:39 UTC, arajajyothibabu requested changes

2024-01-10 13:39 UTC, arajajyothibabu commented on src/app/layout.tsx
> +              {children}
Remove changes in this file

2024-01-10 13:39 UTC, arajajyothibabu commented on src/app/globals.css
> +
revert this change

2024-01-10 13:39 UTC, arajajyothibabu commented on prisma/schema.prisma
> +
revert this change

2024-01-11 05:54 UTC, tulasikurete commented
![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/0fe8f5e5-c65c-4ef6-80da-47317a7c75fe)

2024-01-11 07:02 UTC, arajajyothibabu approved these changes

2024-01-11 07:02 UTC, merged