adding sider
trisandyatechnologies/ecom pull request #2
Opened 2023-12-23 06:12 UTC by tulasikurete

sider
![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/c88122ee-662e-416d-9cc2-582fef119940)

2023-12-26 09:54 UTC, Namahsivaya7 requested changes

2023-12-26 09:54 UTC, Namahsivaya7 commented on src/app/components/Sider.tsx
> +            <Space>
please remove duplicate "space" tag

2023-12-26 09:54 UTC, Namahsivaya7 commented on src/app/components/Sider.tsx
> +        <section>
please remove duplicate tag

2023-12-26 09:54 UTC, Namahsivaya7 commented on src/app/components/Sider.tsx
> +            <Panel header={<Typography>color</Typography>} key="1">
could you please remove "typography" tag which assign to header

2024-01-02 06:24 UTC, tulasikurete commented
![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/24e8077b-5489-4ce7-a840-ef920077034f)

2024-01-03 05:05 UTC, NagaDurga16 requested changes

2024-01-03 05:05 UTC, NagaDurga16 commented on src/app/components/Sider.tsx
> +    // console.log(key);
please remove this

2024-01-03 05:05 UTC, NagaDurga16 commented on src/app/components/Sider.tsx
> +      <section>
please remove this sections

2024-01-03 07:23 UTC, tulasikurete commented
![image](https://github.com/trisandyatechnologies/ecom/assets/144014053/4ddba453-4038-44eb-8976-f8b9c5d17e4f)

2024-01-03 07:24 UTC, NagaDurga16 approved these changes

2024-01-03 10:42 UTC, arajajyothibabu approved these changes
LGTM, congrats on your first PR 🎉

2024-01-03 10:43 UTC, merged