Authentication Pages
trisandyatechnologies/ecom pull request #3
Opened 2023-12-26 05:23 UTC by saiganesharaja

![Screenshot from 2023-12-26 10-51-44](https://github.com/trisandyatechnologies/ecom/assets/140064943/6c6eb6ec-925d-4bba-8dc1-aa750808e40c)
![Screenshot from 2023-12-26 10-52-52](https://github.com/trisandyatechnologies/ecom/assets/140064943/87e73c23-f196-4ce9-b548-4eb7a43a7887)

2023-12-26 09:50 UTC, NagaDurga16 commented on src/app/signin/page.tsx
> +const App: React.FC = () => {
change function name to signin

2023-12-26 09:51 UTC, NagaDurga16 commented on src/app/signin/page.tsx
> +const App: React.FC = () => {
please change name

2023-12-26 09:51 UTC, tulasikurete commented on src/app/signin/page.tsx
> +const App: React.FC = () => {
change function name

2023-12-26 09:51 UTC, NagaDurga16 commented on src/app/signup/page.tsx
> +const App: React.FC = () => {
please change function name

2024-01-02 06:12 UTC, NagaDurga16 commented
Please remove rating file in authentication branch

2024-01-03 05:15 UTC, tulasikurete approved these changes

2024-01-03 05:25 UTC, NagaDurga16 approved these changes

2024-01-03 05:54 UTC, arajajyothibabu requested changes

2024-01-03 05:54 UTC, arajajyothibabu commented on src/app/cart/page.tsx
> +
Why cartitem removed here?

2024-01-03 05:54 UTC, arajajyothibabu commented on src/app/page.tsx
> +import Rating from "./components/Rating";
Why Rating came here ?

2024-01-03 05:54 UTC, arajajyothibabu commented on src/app/page.tsx
> +      <Rating/>
Remove rating changes from this branch

2024-01-03 05:55 UTC, NagaDurga16 requested changes
remove rating page

2024-01-03 06:03 UTC, NagaDurga16 approved these changes
remove rating page

2024-01-03 06:14 UTC, saiganesharaja commented
![Screenshot from 2024-01-03 11-43-01](https://github.com/trisandyatechnologies/ecom/assets/140064943/f5915c24-b8e7-430c-8896-4ee1a9d71302)

2024-01-03 07:30 UTC, tulasikurete approved these changes

2024-01-03 11:11 UTC, arajajyothibabu approved these changes

2024-01-03 11:11 UTC, merged