Product page
trisandyatechnologies/ecom pull request #9
Opened 2024-01-03 05:26 UTC by Namahsivaya7

![Screenshot (78)](https://github.com/trisandyatechnologies/ecom/assets/140064885/684bb418-275e-4fb9-a16e-5491ce1f10b5)

2024-01-03 05:32 UTC, NagaDurga16 requested changes

2024-01-03 05:32 UTC, NagaDurga16 commented on src/app/layout.tsx
> +            {/* <Sider
please remove unwanted code

2024-01-03 06:17 UTC, Namahsivaya7 commented
![Screenshot (81)](https://github.com/trisandyatechnologies/ecom/assets/140064885/e12a68b3-f1d2-4d00-b24c-37092f543b35)

2024-01-03 06:22 UTC, Namahsivaya7 commented
![Screenshot (79)](https://github.com/trisandyatechnologies/ecom/assets/140064885/32de396c-6052-4bd8-8bbf-8bdfcfe3dd23)
![Screenshot (80)](https://github.com/trisandyatechnologies/ecom/assets/140064885/5c5e0110-d9cc-43fc-aa5f-fdc453890bd5)
![Screenshot (81)](https://github.com/trisandyatechnologies/ecom/assets/140064885/94eff8a5-ff9c-439b-9943-2bbde95d665a)

2024-01-03 07:03 UTC, Namahsivaya7 commented
![Screenshot (82)](https://github.com/trisandyatechnologies/ecom/assets/140064885/eb884eb6-6084-466a-8862-e9c831c56892)
![Screenshot (83)](https://github.com/trisandyatechnologies/ecom/assets/140064885/fa75e485-1821-45e3-b4f4-1e57f7728e5c)

2024-01-03 07:10 UTC, NagaDurga16 approved these changes, later dismissed

2024-01-03 07:25 UTC, tulasikurete approved these changes

2024-01-03 10:58 UTC, Namahsivaya7 commented
![Screenshot (84)](https://github.com/trisandyatechnologies/ecom/assets/140064885/6381ae25-1866-4cc4-a601-9850c80a622d)

2024-01-03 11:02 UTC, NagaDurga16 approved these changes

2024-01-12 10:24 UTC, Namahsivaya7 commented
![Screenshot (86)](https://github.com/trisandyatechnologies/ecom/assets/140064885/1b62f8ee-7893-4aa0-b997-53163871953d)
![Screenshot (87)](https://github.com/trisandyatechnologies/ecom/assets/140064885/c513bf1f-d046-4154-8e94-2fba072ecab0)

2024-01-12 13:58 UTC, arajajyothibabu approved these changes

2024-01-12 13:59 UTC, merged